[package]
name = "mff-thesis"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Martin Rosenberg"]
license = "CC0"
description = "Thesis template for MFF CUNI (Charles University, Faculty of Mathematics and Physics)"
keywords = ["thesis", "template", "university", "charles-university", "mff", "cuni"]
categories = ["paper"]
disciplines = ["education"]
compiler = "0.14.0"

[template]
path = "template"
entrypoint = "thesis.typ"
